---
title: "Integration of morphological features"
output: html_document
date: '2023-05-18'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scuttle)
library("FactoMineR")
library("factoextra")
```

In this RMD file, we will perform clustering on the curated data (after excluding cells that swam off between IF and IMC and segmentation artifacts) with the integration of morphological features.

```{r read-data}

path <- "/mnt/Multimodal_Imaging_Daria/_Data_Analysis/_tmp_daria/Image_analysis/20230112_DIMR_Ilastik/20230312_sc_data_combined"

spe <- readRDS(file.path(path,"data/spe_1px_wo-ghosts.rds"))

```

Then we will generate matrices from morphological and intensity features alone and combined. 

```{r generate-dataframes, message=FALSE, fig.height=7}
library(bruceR)
library(SpatialExperiment)

morph_names <- c("area",
                 "area_convex",
                 "area_filled",
                 "axis_major_length",
                 "axis_minor_length",
                 "eccentricity",
                 "equivalent_diameter_area",
                 "perimeter",
                 "solidity",
                 "assymetry",
                 "concavity",
                 "fill",
                 "aspect_ratio-0",
                 "perimeter_ratio-0")

# morph_names <- c("area",
#                  "eccentricity"
# )

robustScaler <- function(data, upper, lower) {
  scaled_data <- (data-median(data))/(quantile(data, probs = c(upper)) - quantile(data, probs = c(lower)))
  return(scaled_data)
}

zscore_Scaler <- function(data) {
  scaled_data <- (data-mean(data))/sd(data)
  return(scaled_data)
}

clipScaler <- function(data, upper, lower, min, max) {
  data[data > quantile(data, probs = c(upper))] <- quantile(data, probs = c(upper))
  data[data < quantile(data, probs = c(lower))] <- quantile(data, probs = c(lower))
  scaled_data <- RESCALE(data, to=min:max)
  return(scaled_data)
}

intensity_mat <- assay(spe, "exprs")
colnames(intensity_mat) <- spe$sample
intensity_mat <- intensity_mat[!grepl("mean-80", rownames(intensity_mat)),]

intensity_mat_hq <- intensity_mat[!grepl("IDO|DAPI|2IF_GD2|3IF_CD56|DNA1|H4K12Ac|H3K9Ac|CXCR2|PNMT|Fibro", rownames(intensity_mat)),]
intensity_mat_lq <- intensity_mat[grepl("IDO|DAPI|2IF_GD2|3IF_CD56|DNA1|H4K12Ac|H3K9Ac|CXCR2|PNMT|Fibro", rownames(intensity_mat)),]

#Make sure to exclude cells that are zero for all markers as PG won't work otherwise
non_zeros <- as.logical(colSums(intensity_mat_hq)!=0)

intensity_mat_hq_wo_zeros <- intensity_mat_hq[,non_zeros]
intensity_mat_lq_wo_zeros <- intensity_mat_lq[,non_zeros]
spe <- spe[,non_zeros]


cell_id <- colnames(spe)
tissue <- spe$tissue

morph_mat <- as.matrix(t(colData(spe)[,morph_names]))
rownames(morph_mat) <- gsub('-0','',rownames(morph_mat))
morph_mat_scaled <- t(apply(morph_mat, 1, RESCALE, to=0:1))
colnames(morph_mat_scaled) <- spe$sample


features_mat <- rbind(intensity_mat_hq, morph_mat_scaled)

```

