## Load data

First, we will read in the previously `SpatialExperiment`
object generated before any background correction or normalization was done on IMC images.

```{r read-data-scviz, message=FALSE}
path <- "/mnt/Multimodal_Imaging_Daria/PIPELINE/NEWEST_RESULTS/results/Manuscript/1_Ext_Figure"

spe <- readRDS(file.path(path, "spe_unprocessed-images.rds"))
```

Let's first color the dots by sample in UMAP space for PT and BM seperately.

```{r visualizing-sample-tissue-sep, message=FALSE, fig.width=10, fig.height=10}

library(dittoSeq)
library(scater)
library(patchwork)
library(cowplot)
library(viridis)

tissue <- "BM"

## UMAP colored by sample
col_vector_433 <- colors()[grep('gr(a|e)y', grDevices::colors(), invert = T)]
col_sample <- setNames(sample(col_vector_433, length(unique(spe[, spe$tissue==tissue]$sample))), unique(spe[, spe$tissue==tissue]$sample))

values <- unique(spe$tissue)
spe$binary <- NA
spe$binary <- spe$tissue == tissue

background <- as.data.frame(reducedDim(spe[,spe$binary == FALSE], "UMAP"))
foreground <- as.data.frame(reducedDim(spe[,spe$binary == TRUE], "UMAP"))
foreground$sample <- spe[,spe$binary == TRUE]$sample
foreground <-  foreground[sample(nrow(foreground)),]

p1 <- ggplot(background, aes(x=V1, y=V2) ) +
  geom_point(color="gray90", size=0.3, show.legend=F) + 
  geom_point(data=foreground, mapping=aes(x=V1, y=V2, color=sample), size=0.3, show.legend=F) + 
  scale_color_manual(values = col_sample) +
  ggtitle(values[i]) +
  theme(plot.title = element_text(size = 4), 
        axis.title = element_text(size=4), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))

p2 <- ggplot(background, aes(x=V1, y=V2) ) +
  geom_point(color="gray90", size=0.3, show.legend=F) + 
  geom_point(data=foreground, mapping=aes(x=V1, y=V2, color=sample), size=0.3, show.legend=T) + 
  scale_color_manual(values = col_sample) +
  ggtitle(values[i]) +
  theme(plot.title = element_text(size = 4), 
        axis.title = element_text(size=4), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))

tiff(filename = file.path(path, paste0("R/before_UMAP_", tissue, "_sample.tiff")),
     width = 95, height = 95, units = "mm", res=600)
p1
dev.off()

tiff(filename = file.path(path, paste0("R/before_UMAP_", tissue, "_sample_legend.tiff")),
     width = 595, height = 295, units = "mm", res=300)
p2
dev.off()
```

Let's now look at density plots visualizing old and new samples.

```{r visualizing-density-by-samples, message=FALSE, fig.width=7, fig.height=20}

library(viridis)
library(cowplot)

spe$discrete <- NA
spe[,as.integer(spe$year) <= 11]$discrete <- "old" 
spe[,as.integer(spe$year) > 11]$discrete <- "new" 
spe[,spe$tissue=="PT"]$discrete <- "PT" 

values <- unique(spe$discrete)

plot_list <- list()
var <- "discrete"

for(i in 1: length(values)){
  spe$binary <- spe[[var]] == values[i] 
  
  background <- as.data.frame(reducedDim(spe, "UMAP"))
  foreground <- as.data.frame(reducedDim(spe[,spe$binary == TRUE], "UMAP"))
  plot_list[[i]] <- ggplot(background, aes(x=V1, y=V2) ) +
    geom_point(color="gray90", size=0.3) + 
    stat_density_2d(mapping=aes(fill = ..level..), data=foreground, geom = "polygon", show.legend=F) +
    ggtitle(values[i]) +
    scale_fill_continuous(type = "viridis") +
    theme(plot.title = element_text(size = 4), 
          axis.title = element_text(size=4), 
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank(), 
          axis.line = element_line(colour = "black"))

}

tiff(filename = file.path(path, paste0("R/before_UMAP_density_", values[2], ".tiff")),
   width = 95, height = 95, units = "mm", res=600)
plot_list[[2]]
dev.off()

tiff(filename = file.path(path, paste0("R/before_UMAP_density_", values[1], ".tiff")),
   width = 95, height = 95, units = "mm", res=600)
plot_list[[1]]
dev.off()
```

Then we will visualize the nuclear expression in BM samples.

```{r visualizing-nuclear_int, message=FALSE, fig.width=10, fig.height=10}

values <- unique(spe$tissue)
spe$binary <- NA
spe$binary <- spe$tissue == "BM" 

background <- as.data.frame(reducedDim(spe[,spe$binary == FALSE], "UMAP"))
foreground <- as.data.frame(reducedDim(spe[,spe$binary == TRUE], "UMAP"))
foreground$nuclear <- t(assay(spe["Histone H3K9Ac",spe$binary == TRUE], "exprs"))
names(foreground)[3] <- "nuclear"
foreground <-  foreground[sample(nrow(foreground)),]

p <- ggplot(background, aes(x=V1, y=V2) ) +
  geom_point(color="gray90", size=0.3, show.legend=F) + 
  geom_point(data=foreground, mapping=aes(x=V1, y=V2, color=nuclear), size=0.3, show.legend=F) + 
  scale_color_viridis() +
  ggtitle(values[i]) +
  theme(plot.title = element_text(size = 4), 
        axis.title = element_text(size=4), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))

tiff(filename = file.path(path, "R/before_UMAP_nuclear.tiff"),
   width = 95, height = 95, units = "mm", res=600)
p
dev.off()

```