---
title: "MapMet project: Exploratory analysis"
author: "Sara Wernig-Zorc"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_depth: 5
    toc_float: yes
    collapsed: false
    code_folding: hide
    highlight: pygments
    theme: spacelab
    df_print: paged
params:
  input: "/home/data/MapMet/"
  out: "/home/out/MapMet/"
  GO_db: "/home/sara_wz/annotation/GSEA_GeneSetEnrichments"
  markers: "/home/sara_wz/annotation/MES_ADRN/"
  nicheNetDB: "/home/sara_wz/annotation/multiNicheNetDB/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = FALSE, 
                      messages = FALSE,
                      warning = FALSE)

library(parallel)
future::plan(strategy = 'future::multicore', workers = 20)
options(future.globals.maxSize = 8 * 10^9)

source("/home/sara_wz/MapMet_project/MapMetSC/code/R/CCC_analysis/00_MapMet_color_code.R")

print(params)
```


```{r libs}
suppressPackageStartupMessages(library('Seurat'))
suppressPackageStartupMessages(library('SingleCellExperiment'))
suppressPackageStartupMessages(library('dplyr'))
suppressPackageStartupMessages(library('ggplot2'))
suppressPackageStartupMessages(library('igraph'))
suppressPackageStartupMessages(library('SCpubr'))
suppressPackageStartupMessages(library('viridis'))
suppressPackageStartupMessages(library('scCustomize'))
suppressPackageStartupMessages(library('RColorBrewer'))
suppressPackageStartupMessages(library('SCpubr'))
```

```{r eval=FALSE, include=FALSE}
metadata <- readRDS(paste0(params$input,
                           "/fetahu.scRNA.2023/data/metadata.rds"))

scrna_data <- readRDS(paste0(params$input,
                             "/fetahu.scRNA.2023/data/rna_decontaminated.rds"))

rna <- as.Seurat(scrna_data, data=NULL)
rna <- RenameAssays(object = rna, originalexp = 'RNA')

rna@active.ident <- setNames(pull(metadata[match(metadata$cell,colnames(rna)),
                                           "cellont_cluster"], 
                                  "cellont_cluster"),
                             pull(metadata[match(metadata$cell,colnames(rna)), 
                                           "cell"], 
                                  "cell"))

DefaultAssay(rna) <- "RNA"

true_label <- rna@active.ident
rna$original_celltype <- rna@active.ident

###############################################################################

fetahu2023_tumorClust <- subset(rna, 
                                original_celltype == "NB (8)")

fetahu2023_tumorClust <- 
  fetahu2023_tumorClust %>% 
  NormalizeData(normalization.method = "LogNormalize", 
                scale.factor = 10000) %>%  
  ScaleData() 


saveRDS(fetahu2023_tumorClust, 
        file = paste0(params$out,"Rds/fetahu.scRNA.tumor.cluster.Rds"))

```

```{r}
fetahu2023_tumorClust <- readRDS(paste0(params$out,"Rds/fetahu.scRNA.tumor.cluster.Rds"))
```

```{r}
IMCtoRNA <- read_delim(paste0(
  params$data,"lazic.imc.2024/gene_list/protein2gene_2024-05-03.csv"),
                       delim = ";")

stem_markers <- c("POU5F1", "MYC", "KLF4", "SOX2")

undiff_neuroblast <- "ALK"

# General Neuroblastoma cell markers
NB_markers <- c("ELAVL4","PHOX2B","PHOX2A","TH","SYP","CHGA", 
                "CHGB","DBH","GATA2","MYCN","L1CAM") 
```

```{r}
DimPlot(fetahu2023_tumorClust)

FeaturePlot(fetahu2023_tumorClust, features = "NCAM1")
FeaturePlot(fetahu2023_tumorClust, features = "CD24")
FeaturePlot(fetahu2023_tumorClust, features = "B4GALNT1")
```

```{r}
FeatureScatter(
  fetahu2023_tumorClust,
  "NCAM1",
  "CD24",slot = "data")
```

```{r}
FeaturePlot(fetahu2023_tumorClust, features = stem_markers)
```

```{r}
all_tumor_cells <- c("B4GALNT1","ST8SIA1","NCAM1")
diff_tumor_cells <- c("CD44", "VIM","FN1","LUM", "CHGA","PNMT", 
               "ELAVL4", "PRPH","GATA3",  "S100B","SOX10")
gene_of_interest <- "CD24"

IMC_genes <- c("B4GALNT1","ST8SIA1","NCAM1","CD24", # general tumor cells
               "CD44", # MES or ADR tumor cells, depends on who you ask :) 
               "VIM","FN1","LUM", # MES - like tumor cells
               "CHGA","PNMT", # CHC - like tumor cells
               "ELAVL4", "PRPH","GATA3", # SYM - like tumor cells
               "S100B","SOX10") # SCP - like tumor cells

```



One strategy i am testing is creating "cell state signatures" and trying to define 
the lineage marker low expressing NB cells (with or without CD24 expression)

```{r}
fetahu2023_tumorClust <- AddModuleScore(fetahu2023_tumorClust, 
                                        features = stem_markers,
                                        seed = 2805,
                                        name = "stemness_score")

fetahu2023_tumorClust <- AddModuleScore(fetahu2023_tumorClust, 
                                        features = all_tumor_cells,
                                        seed = 2805,
                                        name = "all_NB_cells")

fetahu2023_tumorClust <- AddModuleScore(fetahu2023_tumorClust, 
                                        features = diff_tumor_cells,
                                        seed = 2805,
                                        name = "diff_NB_cells")

fetahu2023_tumorClust <- AddModuleScore(fetahu2023_tumorClust, 
                                        features = "CD24",
                                        seed = 2805,
                                        name = "CD24_expression")
```

```{r}
module_scores_combined <- c("General NB score" = "all_NB_cells1",
                            "Lineage-specific NB score" = "diff_NB_cells1",
                            "CD24 expression" = "CD24_expression1",
                            "General stemness score" = "stemness_score1")

#COLOR_CODE_DOTPLOT <- c("")





DotPlot(fetahu2023_tumorClust, 
        features = module_scores_combined,
        cols = c("lightblue","red")) +
        theme(axis.text.x = element_text(angle = 45,hjust=1, size = 16)) + 
        RotatedAxis() + scale_size(range = c(1,8)) 



VlnPlot(fetahu2023_tumorClust, 
        features = c(all_tumor_cells, diff_tumor_cells, gene_of_interest))
```

```{r}
saveRDS(fetahu2023_tumorClust, 
        file = paste0(params$out,"Rds/fetahu.scRNA.tumor.cluster_v12-2024.Rds"))
```

