---
title: "Pseudoananymizing metadata"
output: html_document
date: '2024-01-04'
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "120%")
```

## Load data

```{r define-color-code, message=FALSE}

library(openxlsx)
library(dplyr)

path <- "/mnt/Multimodal_Imaging_Daria/PIPELINE/NEWEST_RESULTS"
meta_path <- file.path('/mnt/Multimodal_Imaging_Daria/archive/metadata/20240604_metadata_complete.csv')
meta_all = read.csv(meta_path)

custom_order <- c("PTDE", "BMDE", "BMRE1", "BMRE2", "BMREL", "BM")
meta_all$order <- factor(paste0(meta_all$Tissue, meta_all$Timepoint), levels=custom_order)
meta_all <- meta_all[order(meta_all$order), ]

#Anonymize sample ID
codes <- setNames(paste0(sapply(strsplit(unique(meta_all$Sample), "-"), `[`, 1), "-", sprintf("%03d", 1: length(unique(meta_all$Sample)))), unique(meta_all$Sample))
anon_sample_id <- recode(meta_all$Sample, !!!codes)

#Anonymize study ID
meta_all[meta_all$control=="yes",]$Study_ID <- "na"
codes <- setNames(paste0("Patient_", sprintf("%03d", 1: length(unique(meta_all$Study_ID)))), unique(meta_all$Study_ID))
codes["na"] <- ""
anon_study_id <- recode(meta_all$Study_ID, !!!codes)

#Anonymize stainer
codes <- setNames(paste0("Stainer_", 1: length(unique(meta_all$Stainer))), unique(meta_all$Stainer))
anon_stainer <- recode(meta_all$Stainer, !!!codes)

meta_all$Patient_ID <- anon_study_id
meta_all$Sample_ID <- anon_sample_id
meta_all$Stainer <- anon_stainer

#Save metadata with anonoymization codes for later reference
#meta_all <- select(meta_all, -X)
write.csv(meta_all, file.path(path, "results/Manuscript/1_Figure/R/20240604_Suppl_Table1_anonymization-codes.csv"))

#Save metadata with only anonymized IDs 
meta_anon <- select(meta_all, -c("Sample", "Study_ID"))
names(meta_anon)[names(meta_anon) == 'Sample_ID'] <- 'Sample'
names(meta_anon)[names(meta_anon) == 'Patient_ID'] <- 'Study_ID'
write.csv(meta_anon, file.path(path, "results/Manuscript/1_Figure/R/20240604_metadata_complete_anon.csv"))

#Save metadata split by sample_metadata, clinical and genetic patient metadata
meta_sample <- meta_all[,c("Sample_ID", "Patient_ID", "Tissue", "control", "Timepoint", "Puncture_side", "Infiltration_right", "Infiltration_left", "Staining_date", "Stainer", "IMC_date", "IMC_score", "exclude")]          
meta_patient_clinical <- meta_all[meta_all$control=="no",c("Patient_ID", "stage4", "rez_dat", "prog_dat", "event_dat", "tod_dat1", "efs", "tod", "efs_dur", "tod_dur", "age_at_diag", "therapy", "Gender")]
names(meta_patient_clinical)[names(meta_patient_clinical) == 'stage4'] <- 'stage'
meta_patient_clinical <- distinct(meta_patient_clinical)

meta_patient_genetic <- meta_all[meta_all$control=="no",c("Patient_ID", "X1p_loss", "X1q_gain", "X1q_loss", "X2p_gain", "X3p_loss", "X3q_loss", "X4p_loss", "X6q_loss", "X7q_gain", "PTPRD_del", "CDKN2AB_del", "X11q_loss", "X12q_gain", "X14q_loss", "X17p_loss", "X17q_gain", "X19p_loss", "X19q_loss", "X22q_loss", "MYCN_amp", "TERT_rear", "ATRX_del", "ALK_amp", "ALK_mut")]
meta_patient_genetic <- distinct(meta_patient_genetic)


list_of_datasets <- list("sample_spec_metadata" = meta_sample, "patient_spec_clinical" = meta_patient_clinical, "patient_spec_genetic" = meta_patient_genetic)
write.xlsx(list_of_datasets, file = file.path(path, "results/Manuscript/1_Figure/R/20240604_Suppl_Table1.xlsx"))
```

