---
title: "Pseudoananymizing metadata"
output: html_document
date: '2024-01-04'
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "120%")
```

## Load data

```{r define-color-code, message=FALSE}

library(openxlsx)
library(dplyr)

path <- "/mnt/Multimodal_Imaging_Daria/PIPELINE/NEWEST_RESULTS/results/Manuscript/1_Figure"

ab_order <- read.csv(file.path(path, "Final_Order_Large_210707_v13_2021-08-27.csv"),sep=";")
ab_cocktail <- read.csv(file.path(path, "NB_cocktail.csv"),sep=";")

name_codes <- c("cleaved PARP"="Cleaved Parp",
                "Vimentin"="VIM", 
                "Histone H3K9Ac"="H3K9Ac",
                "Myeloperoxidase MPO"="MPO",
                "CD8a"="CD8",
                "CD274 (B7-H1- PD-L1)"="PD-L1",
                "CD279 (PD-1)"="PD-1",
                "Indoleamine 2- 3-dioxygenase (IDO)"="IDO",
                "Granzyme B"="GZMB",
                "Fibronectin"="FN1",
                "CXCR2- IL-8 RB"="CXCR2",
                "Chromogranin A"="CHGA")

ab_cocktail$Target <- recode(ab_cocktail$Target, !!!name_codes)

ab_order <- ab_order[ab_order$Antibody%in%ab_cocktail$Target, c("Antibody", "Clone", "Species", "Reactivity", "Concentration", "Storage...C.", "Supplier", "Product.number", "Lot.number..External.")]
ab_order <- distinct(ab_order)
ab_order <- ab_order[!ab_order$Lot.number..External.%in%c("5210706559","277040"),]

ab_cocktail <- ab_cocktail[, c("Metal.Tag", "Target", "Final.Concentration...Dilution")]
ab_cocktail <- distinct(ab_cocktail)

names(ab_order)[names(ab_order) == 'Antibody'] <- 'Target'
merged_ab <- merge(ab_order, ab_cocktail, by = "Target", all = TRUE)
write.xlsx(merged_ab, file = file.path(path, "R/Suppl_Table2.xlsx"))
```

