---
title: "Heatmap - Cytokine Assays"
author: "LazDaria"
date: "`r Sys.Date()`"
output: 
  workflowr::wflow_html
editor_options:
  chunk_output_type: inline
params: 
  path: "/mnt/Multimodal_Imaging_Daria/PIPELINE/NEWEST_RESULTS/results/Manuscript/cytokines"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error=FALSE,
                      messages=FALSE,
                      warning=FALSE)
```

# Heatmap for cytokine assay {#cyto}
In this chapter, we will generate a heatmap for cytokine assays performed using RayBioTech. 

## Load libraries
<details>
   <summary>Load libraries</summary>
   
```{r load-libraries}
library(readxl)
library(dplyr)
library(stringr)
library(tidyr)
library(ComplexHeatmap)
library(viridis)
```
</details>

## Read data
First, we load normalized data from three cytokine assays.

```{r read-data}
data_inf <- read_excel(file.path(params$path, 'array_all.xlsx'), sheet = "INF3")
data_che <- read_excel(file.path(params$path, 'array_all.xlsx'), sheet = "CHE1")
data_rec <- read_excel(file.path(params$path, 'array_all.xlsx'), sheet = "REC1")

head(data_che)
```
## Rename column names

```{r rename-col}
# Rename columns: remove dots and numbers, replace spaces with underscores
clean_colnames <- function(colname) {
  colname %>%
    str_replace_all("\\.\\d*$", "") %>%  # Remove trailing numbers after a dot
    str_replace_all("\\.\\.\\.+\\d*", "") %>%  # Remove dots and trailing numbers
    str_replace_all(" ", "_")                  # Replace spaces with underscores
}

# Apply the renaming function
colnames(data_inf) <- sapply(colnames(data_inf), clean_colnames)
colnames(data_che) <- sapply(colnames(data_che), clean_colnames)
colnames(data_rec) <- sapply(colnames(data_rec), clean_colnames)
```

## Compute mean between duplicate rows

```{r mean-duplicate-rows}
# Combine duplicate columns by calculating the mean
combine_duplicate_columns <- function(df) {
  df %>%
     pivot_longer(-Normalization, names_to = "colname", values_to = "value") %>%
     group_by(Normalization, colname) %>%
     summarise(mean_value = mean(value, na.rm = TRUE), .groups = 'drop') %>%
     pivot_wider(names_from = colname, values_from = mean_value)
}

# Apply the function to combine duplicate columns
data_combined_inf <- combine_duplicate_columns(data_inf)
data_combined_che <- combine_duplicate_columns(data_che)
data_combined_rec <- combine_duplicate_columns(data_rec)

# Remove dots from the column names
colnames(data_combined_inf) <- str_replace_all(colnames(data_combined_inf), "\\.", "")
colnames(data_combined_che) <- str_replace_all(colnames(data_combined_che), "\\.", "")
colnames(data_combined_rec) <- str_replace_all(colnames(data_combined_rec), "\\.", "")

#Set first column as rownames
data_combined_inf <- as.data.frame(data_combined_inf)
rownames(data_combined_inf) <- data_combined_inf$Normalization
data_combined_inf <- data_combined_inf[-1]

data_combined_che <- as.data.frame(data_combined_che)
rownames(data_combined_che) <- data_combined_che$Normalization
data_combined_che <- data_combined_che[-1]

data_combined_rec <- as.data.frame(data_combined_rec)
rownames(data_combined_rec) <- data_combined_rec$Normalization
data_combined_rec <- data_combined_rec[-1]
```

## Filter out columns and rows

```{r filter}
col_filter <- c("R", "PBMC_R", "CHLA", "CHLA_D")
rows_data <- read_excel(file.path(params$path, 'array_all.xlsx'), sheet = "filter")
rows_inf <- rows_data[rows_data$Array=="INF-3","Secreted factor"]
rows_che <- rows_data[rows_data$Array=="CHE-1","Secreted factor"]
rows_rec <- rows_data[rows_data$Array=="REC-1","Secreted factor"]
setdiff(rows_che$`Secreted factor`, rownames(data_combined_che))
```
## Create heatmap 

```{r heatmap-inf-filtered, fig.width=5, fig.height=3}
df <- as.data.frame(data_combined_inf)
row_filter_inf <- rows_inf$`Secreted factor`

Heatmap(scale(t(df[row_filter_inf, col_filter])), 
        column_title = "INF-3-filtered",
        row_order = c("R", "PBMC_R", "CHLA", "CHLA_D"),
        col=viridis(100)
        )
```
```{r heatmap-inf, fig.width=8, fig.height=3}
data_combined_inf <- data_combined_inf %>%
  filter(rownames(data_combined_inf) != "POS-Ave")

df <- as.data.frame(data_combined_inf)

Heatmap(scale(t(df[,col_filter])), 
        column_title = "INF-3_all",
        row_order = c("R", "PBMC_R", "CHLA", "CHLA_D"),
        col=viridis(100)
        )
```

```{r heatmap-che-filtered, fig.width=6, fig.height=3}
df <- as.data.frame(data_combined_che)
row_filter_che <- rows_che$`Secreted factor`

Heatmap(scale(t(df[row_filter_che, col_filter])), 
        column_title = "CHE-1-filtered",
        row_order = c("R", "PBMC_R", "CHLA", "CHLA_D"),
        col=viridis(100)
        )
```

```{r heatmap-che, fig.width=8, fig.height=3}
data_combined_che <- data_combined_che %>%
  filter(rownames(data_combined_che) != "POS-Ave")

df <- as.data.frame(data_combined_che)

Heatmap(scale(t(df[,col_filter])), 
        column_title = "CHE-1-all",
        row_order = c("R", "PBMC_R", "CHLA", "CHLA_D"),
        col=viridis(100)
        )
```

```{r heatmap-rec-filtered, fig.width=3, fig.height=3}
df <- as.data.frame(data_combined_rec)
row_filter_rec <- rows_rec$`Secreted factor`

Heatmap(scale(t(df[row_filter_rec, col_filter])), 
        column_title = "REC-1-filtered",
        row_order = c("R", "PBMC_R", "CHLA", "CHLA_D"),
        col=viridis(100)
        )
```
```{r heatmap-rec, fig.width=8, fig.height=3}
data_combined_rec <- data_combined_rec %>%
  filter(rownames(data_combined_rec) != "POS-Ave")

df <- as.data.frame(data_combined_rec)

Heatmap(scale(t(df[,col_filter])), 
        column_title = "REC-1-all",
        row_order = c("R", "PBMC_R", "CHLA", "CHLA_D"),
        col=viridis(100)
        )
```
```{r heatmap-combined-filtered, fig.width=16, fig.height=3}
data_all <- rbind(data_combined_inf[row_filter_inf,], data_combined_che[row_filter_che,], data_combined_rec[row_filter_rec,])
annot <- c(rep("INF-3", nrow(data_combined_inf[row_filter_inf,])), rep("CHE-1", nrow(data_combined_che[row_filter_che,])), rep("REC-1", nrow(data_combined_rec[row_filter_rec,])))

df <- as.data.frame(data_all)

col_vector <- c("INF-3"="#fc8d59", "CHE-1"="#ffffbf", "REC-1"="#91bfdb")
column_ha <- HeatmapAnnotation(assay = annot, col=list(assay=col_vector))

Heatmap(scale(t(df[,col_filter])), 
        column_title = "all assays-filtered",
        row_order = c("R", "PBMC_R", "CHLA", "CHLA_D"),
        cluster_columns =F,
        top_annotation = column_ha,
        col=viridis(100)
        )
```
```{r heatmap-combined-clustered-filtered, fig.width=16, fig.height=3}
Heatmap(scale(t(df[,col_filter])), 
        column_title = "all assays - filtered (clustered)",
        row_order = c("R", "PBMC_R", "CHLA", "CHLA_D"),
        top_annotation = column_ha,
        col=viridis(100)
        )
```

```{r heatmap-combined-all, fig.width=19, fig.height=3}
data_all <- rbind(data_combined_inf, data_combined_che, data_combined_rec)
annot <- c(rep("INF-3", nrow(data_combined_inf)), rep("CHE-1", nrow(data_combined_che)), rep("REC-1", nrow(data_combined_rec)))

df <- as.data.frame(data_all)

col_vector <- c("INF-3"="#fc8d59", "CHE-1"="#ffffbf", "REC-1"="#91bfdb")
column_ha <- HeatmapAnnotation(assay = annot, col=list(assay=col_vector))

Heatmap(scale(t(df[,col_filter])), 
        column_title = "all assays-all",
        row_order = c("R", "PBMC_R", "CHLA", "CHLA_D"),
        cluster_columns =F,
        top_annotation = column_ha,
        col=viridis(100)
        )
```
```{r heatmap-combined-clustered-all, fig.width=19, fig.height=3}
Heatmap(scale(t(df[,col_filter])), 
        column_title = "all assays - all (clustered)",
        row_order = c("R", "PBMC_R", "CHLA", "CHLA_D"),
        top_annotation = column_ha,
        col=viridis(100)
        )
```

## Session Info

<details>
   <summary>SessionInfo</summary>
   
```{r, echo = FALSE}
sessionInfo()
```
</details>
